name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build --if-present
     
    - name: Run tests and linting
      run: |
        npm test
        npx eslint src/**/*.ts
        npx ts-prune

    - name: Zip
      # Add your zipping command here
      # For example: run: zip -r myFiles.zip <source_folder>

      run: zip build.zip dist
      
    - name: Deploy
      run: echo Deploy completed successfully
